name: Issue PR cleaner
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'このIssueは過去30日間に渡り活動がされていないので5日後にcloseします。closeしたくない場合はラベル`stale`を外すかこのコメントを削除してください。'
          stale-pr-message: 'このPRは過去45日間に渡り活動がされていないので10日後にcloseします。closeしたくない場合はラベル`stale`を外すかこのコメントを削除してください。'
          close-issue-message: '`stale`状態から5日経過したのでこちらのIssueはcloseします。'
          close-pr-message: '`stale`状態から10日経過したのでこちらのPRはcloseします。'
          days-before-issue-stale: 30
          days-before-pr-stale: 45
          days-before-issue-close: 5
          days-before-pr-close: 10
          exempt-pr-labels: "milestone"
          exempt-all-pr-milestones: true